### ISSUE TITLE
2 Center Divs turning into 1 div

### ISSUE THREAD

**Issue by akaduwel1** [FlamingoJournal/cse110-sp21-group18#13]
Style the divs so that they are side by side. Then, on a button click, hide the 2 divs and show a center div that takes up the same space as the 2 divs that disappeared.

**Comment by SleepyDeep** [comment]
I Think I did it, basically created new div and deleted the other two. I didn't add demo of text, I think you could just grab the inner html of both and add it to the new div. Formatting would probably be really annoying. One more thing I didn't center the divs in the middle of the page, but I think that should be trivial.  I'm not going to close because I'm not sure if I did it right.
